### ISSUE TITLE
ORCID ID changes author display in Yeti theme

### ISSUE THREAD

**Issue by amandastevens** [NateWr/bootstrap3#105]
When there is no ORCID ID the author names and affiliations are displayed on different lines.
See https://cjb-rcb.ca/index.php/cjb-rcb/article/view/4 

When there is an ORCID ID the author names and affiliations run together. 
See https://cjb-rcb.ca/index.php/cjb-rcb/article/view/72

The site is using the Bootstrap - Yeti theme.

**Comment by NateWr** [comment]
This appears to have been fixed in https://github.com/NateWr/bootstrap3/issues/68. Check that you're running v1.1.1 or above of the Bootstrap3 theme.

(I'll close this issue but let me know if I'm wrong and I'll reopen it.)

**Comment by amandastevens** [comment]
Ah yes, you're right.  I should have looked at closed issues as well as open or tried updating the theme first. You can't see what version of the plugin you're running in the plugin list, but I updated the theme plugin anyway and the issue is fixed.
