### ISSUE TITLE
Theme doesn't not work with 3.1.2

### ISSUE THREAD

**Issue by Letsplaybar** [NateWr/bootstrap3#110]
By the update yesterday, the theme does not work anymore. When is a bug fix expected?

**Comment by asmecher** [comment]
@Letsplaybar, you didn't specify what wasn't working, but when I tried the `master` branch with OJS 3.1.2, I got the following PHP errors:
```
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendpagesindexJournal"  on line 50 "{php}break;{/php}" {php}{/php} tags not allowed. Use SmartyBC to enable them <--
```
https://github.com/NateWr/bootstrap3/pull/111 should resolve this for now; watch for a formal OJS 3.1.2-compatible release to pop up in the OJS Plugin Gallery.

**Comment by NateWr** [comment]
Hi @Letsplaybar, I've created a [release for 3.1.2](https://github.com/NateWr/bootstrap3/releases/tag/3.1.2) now. Can you give it a try and let me know if it resolves the issue that you've had?

Updates for this theme usually follow within a week or so of the release of a new version. I encourage you to look at the [version compatibility chart](https://github.com/NateWr/bootstrap3#version-compatibility) before updating if you're using this theme.

**Comment by Letsplaybar** [comment]
Thanks, the Version 3.1.2 works fine with ojs-3.1.2

**Comment by asmecher** [comment]
Thanks, @Letsplaybar and @NateWr!
