### ISSUE TITLE
Not work on OJS 3.1.2

### ISSUE THREAD

**Issue by navotera** [NateWr/bootstrap3#112]

**Comment by asmecher** [comment]
@navotera, can you describe what doesn't work? Is there an error message or similar? This doesn't give enough information to work with.

**Comment by navotera** [comment]
hi @asmecher 
OJS 3.1.2 does not load any of template file from this theme. 

For example when the page load on the home index, it should load the template file from this theme 
->bootstrap 3 
  -> templates 
      ->frontend
         ->all custom template file such as indexSite.tpl, header.tpl or other partials template files within this theme.

But it does not load any of those custom smarty file (*.tpl) 
And I could say that this is work on the previous version (OJS 3.1.1). 

I curious and install another theme specifically healthscience theme and you know what it does not work too.

**Comment by NateWr** [comment]
Hi @navotera,

That sounds like you have a more general problem with the installation of your themes. Did you install the Health Science theme from the Plugin Gallery under Settings > Website > Plugins? If you install directly from GitHub, make sure you are using the [compatible release package](https://github.com/NateWr/bootstrap3#version-compatibility), and not just downloading the automatic zip of the `master` branch.

**Comment by navotera** [comment]
1. Download the [latest release](https://github.com/NateWr/bootstrap3/releases).
![image](https://user-images.githubusercontent.com/1424851/54352462-b6568500-468c-11e9-91ff-b58dd78e9953.png)

2. Unpack the .zip file and move the `bootstrap3` directory to your OJS installation at `/plugins/themes/bootstrap3`.
![image](https://user-images.githubusercontent.com/1424851/54352523-d2f2bd00-468c-11e9-89d3-37ed8646c862.png)

3. Login to the admin area of your OJS website. Browse to the `Settings` > `Website` > `Plugins` page and enable the Bootstrap 3 theme.
![image](https://user-images.githubusercontent.com/1424851/54352614-05041f00-468d-11e9-8b2f-09842fa30315.png)


4. Browse to the `Settings` > `Website` > `Appearance` page and select Bootstrap 3 from the theme option and save your change.
![image](https://user-images.githubusercontent.com/1424851/54352652-1d743980-468d-11e9-884c-84a697c20f85.png)


5. Result : 
![image](https://user-images.githubusercontent.com/1424851/54352673-282ece80-468d-11e9-8cd4-bcf9725bdb32.png)

**Comment by mpbraendle** [comment]
Tried the plugin, too. The following error is generated:
[15-Mar-2019 11:55:29 UTC] PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendpagesindexJournal"  on line 50 "{php}break;{/php}" {php}{/php} tags not allowed. Use SmartyBC to enable them <-- 
  thrown in /usr/local/service/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 50

**Comment by mpbraendle** [comment]
Which is in templates/frontend/pages/indexJournal.tpl
I'm trying to comment those lines and will report back.

**Comment by mpbraendle** [comment]
Also: 
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendcomponentsnavigat"  on line 20 "{php}continue;{/php}" {php}{/php} tags not allowed. Use SmartyBC to enable them <-- 
  thrown in /usr/local/service/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 20

Which is in templates/frontend/components/navigationMenu.tpl

PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendobjectsarticlesum"  on line 70 "{php}continue;{/php}" {php}{/php} tags not allowed. Use SmartyBC to enable them <-- 
  thrown in /usr/local/service/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 70

in templates/frontend/objects/article_summary.tpl

**Comment by mpbraendle** [comment]
If one comments the offending lines (with {* *} ) the home page of the journals is shown in the chose Bootstrap theme.

Looks like there are some old tags used in the templates which require the Smarty Backwards Compatibility turned on.
Either the templates must be fixed to be Smarty3-compliant or the SmartyBC must be included.

**Comment by navotera** [comment]
hi mr @mpbraendle 

I never found such error on my apache error log. 

are you sure you used the latest version of this theme ?

**Comment by mpbraendle** [comment]
You are correct. My plugin was still on 3.1.1 (probably copied it over).
Did now an upgrade and it works as expected.

**Comment by mpbraendle** [comment]
It is still not clear what happened in your case.
Did you try to upgrade the plugin using the Plugin Gallery? You should try to do so (enable write permission on plugins, themes, and bootstrap3 directory temporarily)

**Comment by navotera** [comment]
I am not upgrading theme just install fresh copy from this github page.

Tried on two computer and both not work.

Have you try it without upgrade, just download the new theme and install to
ojs 3.2.1?

**Comment by mpbraendle** [comment]
In my case, I copied over the plugin from a 3.1.1.4 installation, then did the upgrade via plugin gallery. Works perfectly.
I recommend you to use the plugin gallery, too. Sometimes getting plugins from Github may not install all dependencies (although that will probably not be the cause for this plugin).

**Comment by navotera** [comment]
What os, webserver, php version do you use?

**Comment by navotera** [comment]
this is bug on OJS 3.1.2. 

And already fixed by vitaly 
https://github.com/pkp/pkp-lib/issues/4600

**Comment by NateWr** [comment]
@navotera glad you were able to get it working. A quick note about this step you shared:

![](https://user-images.githubusercontent.com/1424851/54352462-b6568500-468c-11e9-91ff-b58dd78e9953.png)

When downloading a release, **always** use the `bootstrap3-<version>.tar.gz` file. This is the package that is intended for distribution. The "source code" files are added automatically by github and i don't know how to remove them, but they will usually lead to an error in the name of the plugin folder.

**Comment by navotera** [comment]
Thank for your guide @NateWr 

Hope it would have benefit for others user too
