### ISSUE TITLE
Bootstrap3 ver 3.1.2 Error with OJS 3.1.2 loading jQuery 3.3.1

### ISSUE THREAD

**Issue by roydegler** [NateWr/bootstrap3#114]
I have installed the theme version 3.1.2 but I am getting an error:  Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

I see that OJS is loading jQuery 3.3.1 via cdn.  

How do I get OJS to use a different version of jQuery or will that break the app?

Thanks
Roy

**Comment by NateWr** [comment]
Ah, good catch.

Don't modify the jQuery version that OJS is using or you will likely break the backend. We'll need to specify a version for the frontend.

Can you try modifying [these two lines of code](https://github.com/NateWr/bootstrap3/blob/master/BootstrapThreeThemePlugin.inc.php#L71-L72): 

$jquery = '//ajax.googleapis.com/ajax/libs/jquery/' . CDN_JQUERY_VERSION . '/jquery' . $min . '.js';
$jqueryUI = '//ajax.googleapis.com/ajax/libs/jqueryui/' . CDN_JQUERY_UI_VERSION . '/jquery-ui' . $min . '.js';

Change them to:

$jquery = '//http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery' . $min '.js';
$jqueryUI = '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui' . $min . '.js';

Give that a test and let me know if you see any adverse effects. If not, I'll roll that change into the plugin, include the files for those not running a CDN, and put out a new release.

**Comment by briho** [comment]
I was just grappling with the same problem.

I changed the code per your instructions and the site stopped functioning with this appearing in the error log: 

> "PHP Parse error:  syntax error, unexpected ''.js'' (T_CONSTANT_ENCAPSED_STRING) in /[xxx]/plugins/themes/bootstrap3/BootstrapThreeThemePlugin.inc.php on line 71

I'm phenomenally naive about javascript, but I guessed that there was supposed to be a . between $min and '.js'; in the first line of the replacement code. Other than that trivial typo, though, your fix seemed to clear up the problem.

Prior to seeing your recommended fix, I had just replaced the bootstrap.js and bootstrap.min.js files with their 3.4.1 versions and that similarly resolved the errors. Is there any reason not to do that?

**Comment by NateWr** [comment]
> Prior to seeing your recommended fix, I had just replaced the bootstrap.js and bootstrap.min.js files with their 3.4.1 versions and that similarly resolved the errors. Is there any reason not to do that?

No that's probably better!

**Comment by roydegler** [comment]
I will load use bootstrap 3.4.1 and see how it goes.

Thanks
Roy

**Comment by NateWr** [comment]
I've released Bootstrap3 v3.1.2-3 to fix this issue. You can get the [release package](https://github.com/NateWr/bootstrap3/releases/download/3.1.2-3/bootstrap3-3.1.2-3) or look out for it soon in your OJS's plugin gallery.
