### ISSUE TITLE
Registration page needs to be updated to reflect multilingual given and family name 

### ISSUE THREAD

**Issue by bkawula** [NateWr/bootstrap3#116]
Seems like we're no longer using firstName, middleName, lastName:

https://github.com/pkp/pkp-lib/blob/stable-3_1_2/templates/frontend/components/registrationForm.tpl

**Comment by NateWr** [comment]
Thanks for reporting. I've put out a new release (3.1.2.4) to fix this. The update should be available from the Plugin Gallery now.
