### ISSUE TITLE
possibility to export citation data Endnote/Zotero/Mendeley (RIS) is not shown

### ISSUE THREAD

**Issue by annakuglerin** [NateWr/bootstrap3#119]
Although the Einstellungen Citation Style Language-plugin is installed the export of endnote/zotero/mendeley (RIS) data doesn't work. With the standard layout it works

**Comment by NateWr** [comment]
Thanks for reporting, @annakuglerin. It looks like this theme's [article_details.tpl](https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/objects/article_details.tpl#L183-L194) is missing the download citation styles:

https://github.com/pkp/ojs/blob/master/templates/frontend/objects/article_details.tpl#L293-L307

**Comment by dennmuel** [comment]
@annakuglerin: If you're interested, I've addressed this in #137. Sorry, I didn't comment on this issue earlier.
