### ISSUE TITLE
Header.tpl is not loading

### ISSUE THREAD

**Issue by Hassan-Azzam** [NateWr/bootstrap3#120]
I'm using OJS 3.1.2 and i installed the Bootstrap3 Theme.
the theme styles was not loading so i inspected the website and i found that the default header.tpl is what's loading not the bootstrap version of the header.tpl
any idea why that's happening ?

**Comment by asmecher** [comment]
(Also posted at https://forum.pkp.sfu.ca/t/cant-override-header-tpl-template/53791)
