### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by letailli** [NateWr/bootstrap3#145]
Hi everyone,

I installed the last version (3.2.0) of the plugin on a 3.1.2.4 OJS instance.

Some labels are not appearing 
- on the backoffice (which is not a big problem)
![OJS_bootstrap2](https://user-images.githubusercontent.com/2536975/77752117-401e8980-7027-11ea-9e51-0c4e30d3007b.png)

- on the front (which is my main problem)
![OJS_bootstrap](https://user-images.githubusercontent.com/2536975/77752107-38f77b80-7027-11ea-9782-ce8d3cee0e03.png)

Do you have a quick fix in mind ?

**Comment by asmecher** [comment]
@letailli, the 3.2.0 release of the Bootstrap3 plugin is not supposed to be compatible with OJS 3.1.2-4. See the notes on the "Releases" area of the plugin regarding compatibility, or better yet, use the Plugin Gallery to install versions that are marked compatible.

**Comment by letailli** [comment]
Thanks @asmecher 
I guessed so but once you have installed the wrong version you can't downgrade the plugin
I see "ojs2: You are trying to downgrade the product "bootstrap3" from version [3.2.0.0] to version [3.1.2.5]. Downgrades are not supported., referer: http://34.76.75.102/index.php/demo/management/settings/website" in the logs.

I fixed it by using the 3.1.2.5 version of the plugin and changing the version.xml (to make it "looks" like 3.2.0.0). There is no proper way to fix it ?

**Comment by asmecher** [comment]
@letailli, that's a good fix. No, we don't have a way to do this e.g. through the UI for the moment.
