### ISSUE TITLE
Missing or strange affiliation values for newly registered users

### ISSUE THREAD

**Issue by dennmuel** [NateWr/bootstrap3#148]
Hi everyone :)

Transferring [this issue](https://github.com/pkp/pkp-lib/issues/6076) from pkp-lib here... There seems to be a bug with affiliations in OJS 3.2.1-0 and Bootstrap 3.2.0.1.

**Describe the bug**
I registered a new OJS user with information about institution/affiliation, but it did not show up at all in the user profile and it showed up as JSON (I guess?) in the metadata of a submission made by this user.

**To Reproduce**
1. Register a new OJS account for a journal, fill out the affiliation field. Complete the activation of the account.
2. Look into the profile of the new account; the affiliation field is empty. I would expect it to be filled with the value I entered in the registration form.
3. Make a submission with the new account.
4. As e.g. a journal manager, look at the submissions "list of contributors", edit the author derived from the new account, find the affiliation field filled with some strange value somewhat containing the value entered in the registration form.

**What application are you using?**
 OJS version 3.2.1-0
Bootstrap Theme verion 3.2.0.1

**Additional information**
Screenshot of the contact tab in the user profile:
![grafik](https://user-images.githubusercontent.com/21078769/86924962-7bede280-c130-11ea-8ee7-0e7d76851343.png)

Screenshot of the author metadata:
![grafik](https://user-images.githubusercontent.com/21078769/86921554-983b5080-c12b-11ea-84aa-a1191a54d6dd.png)

The journal is bilingual: German (primary) and English. The registration form was filled out in German. The above screenshot is from the English backend, but looks the same in German.

The problem does not occur with the default theme.

Kind regards

**Comment by NateWr** [comment]
> Register a new OJS account

Can I just double-check: this happens when you register an account through the registration form (as a logged out user). Not when you create a user through the editorial backend, right?

**Comment by dennmuel** [comment]
> > Register a new OJS account
> 
> Can I just double-check: this happens when you register an account through the registration form (as a logged out user). Not when you create a user through the editorial backend, right?

Yes, that is correct. Sorry, I didn't make that clear.

**Comment by NateWr** [comment]
Fixed in #152.
