### ISSUE TITLE
Fix display of multilingual keywords

### ISSUE THREAD

**Issue by asmecher** [NateWr/bootstrap3#156]
The `templates/frontend/objects/article_details.tpl` template currently displays keywords from all locales, regardless of the current locale. See https://forum.pkp.sfu.ca/t/ojs-3-2-1-keywords-not-translating/62610 for details.

**Comment by asmecher** [comment]
@NateWr, did this get fixed with a particular commit? The same issue looks like it may affect other themes (e.g. Health Sciences). See https://forum.pkp.sfu.ca/t/healthscience-error-keywords-are-shown-in-both-languages/63076.

**Comment by NateWr** [comment]
I think you're right. And this is the current standard usage in the default theme: https://github.com/pkp/ojs/blob/master/templates/frontend/objects/article_details.tpl#L147-L160

We've tried to track issues across themes in a project, https://github.com/pkp/pkp-lib/projects/17, but I don't think it's been well-maintained. I probably need to take more deliberate oversight of that and keep it in order. I'll file an issue now.

**Comment by NateWr** [comment]
Filed at https://github.com/pkp/pkp-lib/issues/6254
