### ISSUE TITLE
The citationStyleLanguage plugin is not working 100% with this theme

### ISSUE THREAD

**Issue by IWCMoussaS** [NateWr/bootstrap3#160]
Hi
This is our journal
https://journal.iwc.int/index.php/jcrm/article/view/253

The download citation option is not appearing when the Theme is "Bootstrap 3 theme", by changing to another theme like the default theme, I tested that is only with this theme.
Cheers 

<img width="950" alt="notcitationLanguageJavascript" src="https://user-images.githubusercontent.com/61149934/96418299-76ea0600-11ea-11eb-997e-56b6c1b71ae7.png">
<img width="942" alt="citationLanguageJavascript" src="https://user-images.githubusercontent.com/61149934/96418337-8701e580-11ea-11eb-91ec-394df54b5d34.png">

**Comment by NateWr** [comment]
Hi @IWCMoussaS, this was fixed at https://github.com/NateWr/bootstrap3/pull/158 and the fix will be included in the next release.
