### ISSUE TITLE
Backport improved reference display into 3.1.2

### ISSUE THREAD

**Issue by ctgraham** [NateWr/bootstrap3#162]
The plugin's templates for 3.2 improves the display of references in individual HTML tags.
https://github.com/NateWr/bootstrap3/blob/7f2c4b9e8da16a991d570cff6dce21eb182956a2/templates/frontend/objects/article_details.tpl#L382-L396

Core 3.1.2 has an established way to do this:
https://github.com/pkp/ojs/blob/48b59e6abf5865688c058673d69eb4b397847649/templates/frontend/objects/article_details.tpl#L192-L208

It is an easy backport to this plugin.

**Comment by NateWr** [comment]
Thanks, @ctgraham!
