### ISSUE TITLE
Problem with the display of author's information

### ISSUE THREAD

**Issue by letailli** [NateWr/bootstrap3#170]
Hello

We are using the master branch of bootstrap3 with OJS version : 3.2.1-4

We have a little bug in the display of affiliation :

![image](https://user-images.githubusercontent.com/2536975/123268278-31f73b80-d4fe-11eb-9500-46bab8d6b7c5.png)

And the ORCID ID is not displayed at all.

However affiliation and ORCID ID are correctly set for this user
![image](https://user-images.githubusercontent.com/2536975/123268679-8bf80100-d4fe-11eb-8575-452f8983e663.png)

Additional question: is it possible to display the Bio statement ?

I guess the corresponding code is in  templates/frontend/objects/article_details.tpl 

Could you help me to find what's going wrong there ?

Thanks!

```
				{if $publication->getData('authors')}
					<div class="authors">
						{foreach from=$publication->getData('authors') item=author}
							<div class="author">
								<strong>{$author->getFullName()|escape}</strong>
								{if $author->getLocalizedAffiliation()}
									<div class="article-author-affilitation">
										{$author->getLocalizedAffiliation()|escape}
									</div>
								{/if}
								{if $author->getOrcid()}
									<div class="orcid">
										{$orcidIcon}
										<a href="{$author->getOrcid()|escape}" target="_blank">
											{$author->getOrcid()|escape}
										</a>
									</div>
								{/if}

```

**Comment by NateWr** [comment]
Hi @letailli, you shouldn't use the `master` branch in production. Each release of the theme is compatible with only some versions of OJS. It looks like you want Boostrap3 3.2.0.2: https://github.com/pkp/plugin-gallery/blob/main/plugins.xml#L2386-L2401

That can be downloaded here: https://github.com/NateWr/bootstrap3/releases/tag/v3_2_0-2. Can you try to reproduce the issue with that version?

**Comment by letailli** [comment]
Thanks @NateWr.
I switch from branch to tag and I also realize that those information come from the author's information within the publication (not the corresponding user general settings). I do not which one make it works. But it works now. !
Thank
