### ISSUE TITLE
keywords: no separator displayed

### ISSUE THREAD

**Issue by felixhelix** [NateWr/bootstrap3#173]
Hi there, 
For an update I compared the current version with a 3.1.2.0 and noticed that the keywords on the article details page in the current version are lacking separators. 
I looked in the code and found in article_details.tpl								

```
{foreach from=$keywords[$currentLocale] item=keyword}
{foreach name=keywords from=$keyword item=keywordItem}
	{$keywordItem|escape}{if !$smarty.foreach.keywords.last}, {/if}
{/foreach}
{/foreach}
```
Whereas in the standard template it is only
```
{foreach name="keywords" from=$publication->getLocalizedData('keywords') item="keyword"}
{$keyword|escape}{if !$smarty.foreach.keywords.last}{translate key="common.commaListSeparator"}{/if}
{/foreach}	
```
I don't understand what the extra loop is supposed to do but guess it can be removed?

Your's
Felix

**Comment by NateWr** [comment]
It depends on which version of OJS you are running. The latter is more up-to-date from (I think) version 3.2.

**Comment by felixhelix** [comment]
Thanks for your response.
This happens with OJS 3.3.0.7 and bootstrap3 3.2.0.3, as far as I can see these are the latest versions.

**Comment by NateWr** [comment]
Thanks @felixhelix, I think the solution is to adapt the template in Bootstrap3 to be use the `{foreach}` similar to the default theme. The following PR does this. Can you test this change and let me know if it fixes the problem for you?

PR:
https://github.com/NateWr/bootstrap3/pull/174

**Comment by felixhelix** [comment]
Dear @NateWr, 
thanks, yes that fixes the problem for me :-)

**Comment by NateWr** [comment]
Thanks for the confirmation! I've merged that in now.
