### ISSUE TITLE
Darkly theme issues on search page

### ISSUE THREAD

**Issue by OyvindLGjesdal** [NateWr/bootstrap3#183]
Hi,

I noticed these issue after upgrading an OJS 3.1 to OJS 3.3 and using the 3.3 stable branch of this theme.

This is bootstrap 3 base theme and selecting the darkly theme only, image below is from viewing in Chrome.

<img width="1134" alt="darkly" src="https://user-images.githubusercontent.com/5328572/184623766-59010759-ea0f-4e57-83a6-959d700aaead.png">
 
When I change to using other variants than darkly, the search page looks good (but I've only seen light themes).

As far as I can see from inspecting, there are no "user" css rules I've introduced that changes this from the default behaviour: 
<img width="1913" alt="inpsect-from-field" src="https://user-images.githubusercontent.com/5328572/184625383-091fd344-a063-4d0c-9e71-f2182281835a.PNG">

The error seems to happen in Chrome, firefox and partially in IE (the dropdown icon looks correct here, but the text is black)

Thank you very much for still maintaining this theme, even if bootstrap 3 support itself stopped some years ago!

**Comment by NateWr** [comment]
Thanks @OyvindLGjesdal, I've merged to `stable-3_3_0` and cherry-picked forward to the `master` branch.
