### ISSUE TITLE
Search throws error when searching

### ISSUE THREAD

**Issue by OyvindLGjesdal** [NateWr/bootstrap3#185]
After upgrading OJS to 3.3.0.11 (from 3.1) and this plugin to stable-3.3 I get the following error when searching:

```
 Uncaught Error: Call to a member function getBestId() on null in /var/www/ojs/cache/t_compile/2d2f0b6fe9e301f4b66f758b857db3f773774568^7cf1cd52b8ba8108de77f197078de34b733dd394_0.app.frontendobjectsarticlesum.php
```

However when I turn on smarty debugging, it gives me a populated results variable, so I am a bit stumped.

<img width="266" alt="search-debugging-in-smarty" src="https://user-images.githubusercontent.com/5328572/184824168-c44e8635-16b3-47ed-9f89-1b3f3a697fd5.PNG">

The results also has `publishedSubmissions`

<img width="285" alt="publishedSubmission" src="https://user-images.githubusercontent.com/5328572/184826111-2da4bf21-c434-44c9-9d77-6b0f38253f6e.png">

This may be better suited for the pkp forum if it clearly is my user error.

The full strack trace is:
```
Stack trace
#0 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_62fb44d16baca9_09338197()
#1 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#3 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#4 /var/www/ojs/cache/t_compile/2d2f0b6fe9e301f4b66f758b857db3f773774568^756a7119cb48731a8fd45c250b45f4bcca2d6b01_0.app.frontendpagessearch.tpl.php(117): Smarty_Internal_Template->_subTemplateRender() in /var/www/ojs/cache/t_compile/2d2f0b6fe9e301f4b66f758b857db3f773774568^7cf1cd52b8ba8108de77f197078de34b733dd394_0.app.frontendobjectsarticlesum.php on line 26, referer: 
``

`

**Comment by OyvindLGjesdal** [comment]
If I change 

```
-    {foreach from=$results item=result}
+                       {iterate from=results item=result}
                                {include file="frontend/objects/article_summary.tpl" article=$result.publishedSubmission journal=$result.journal showDatePublished=true hideGalleys=true}
-                       {/foreach}
+                       {/iterate}
````
results are shown.

https://github.com/pkp/ojs/blob/stable-3_3_0/templates/frontend/pages/search.tpl#L99 Also uses iterate for the include call.

I don't exactly understand why, but I think foreach doesn't handle an VirtualArrayIterator (which is the type of results) correctly.

**Comment by NateWr** [comment]
Thanks @OyvindLGjesdal! I've merged your PR now. :+1:

**Comment by NateWr** [comment]
(Just a note that I've now cherry-picked this forward to the `master` branch.)
