### ISSUE TITLE
PDF viewer uses only half of screen height

### ISSUE THREAD

**Issue by HighwayStar** [NateWr/bootstrap3#34]
When using Bootstrap 3 theme with current OJS master branch PDF viewer works incorrect and uses only half of screen height.

Browser console produce following warnings:

```
TypeError: options.container is null
http://127.0.0.1:8000/plugins/generic/pdfJsViewer/pdf.js/web/viewer.js
Line 3918


```

```
TypeError: canvas is null
http://127.0.0.1:8000/index.php/test/article/view/1/1
Line 52
```

![bootstrap-pdfbug](https://cloud.githubusercontent.com/assets/1684100/18467314/75a6a0ca-79da-11e6-8f27-a423f4863886.png)

![bootstrap-noconsole](https://cloud.githubusercontent.com/assets/1684100/18467368/af04d094-79da-11e6-833d-9c40112d4ee4.png)

**Comment by NateWr** [comment]
Thanks for reporting @HighwayStar. This looks like something for which additional CSS code will need to be written. I've flagged it as a bug to resolve in a future update.

**Comment by NateWr** [comment]
https://github.com/NateWr/bootstrap3/commit/d119bc549d946587b63c03b688c5434fb32a59f9 fixes this issue by adding some specific CSS. I did it so that it relies on the Bootstrap variables for the navbar height and links, so it should look decent in each of the bundled themes. But it might not fit every one.

**Comment by NateWr** [comment]
The CSS class needs to be adjusted due to a change in the pdfJSViewer submodule.

https://github.com/pkp/pdfJsViewer/commit/bac7af505ec526c23afc867a194d6d15be2d0a54

**Comment by NateWr** [comment]
![issue_view](https://cloud.githubusercontent.com/assets/2306629/22687166/ddb78dca-ed1e-11e6-8fcd-d45d2741dbb5.png)
