### ISSUE TITLE
Logo size

### ISSUE THREAD

**Issue by trenkert** [NateWr/bootstrap3#36]
could you implement an option in the OJS 3 appearance panel to set the size of the journal logo? the bootstrap themes simply scale it down to a very small image.

**Comment by NateWr** [comment]
Hi @trenkert,

The Bootstrap header component only supports a very small logo. Changing this would require overriding the default Bootstrap component, which I'm hesitant to do. Part of the reason we're able to use drop-in Bootstrap themes is that we stick as closely as possible to the default Bootstrap components. If we allowed users to set the size of the logo, we'd break compatibility with all of the bundled themes.

I think this is one of those areas where developers will need to use this theme as a base for further customization. I'm definitely open to hearing ideas for CSS code that would be broadly compatible with the bundled themes.
