### ISSUE TITLE
Missing field 'Contact' with bootstrap3

### ISSUE THREAD

**Issue by Avernial** [NateWr/bootstrap3#38]
Missing field "Contact" inside "About" menu after adding contact via Journal Settings Wizard.

I am using Bootstrap 3 theme with current OJS master branch.

With default theme:

![defaulttheme](https://cloud.githubusercontent.com/assets/1502169/19375281/149557ac-9205-11e6-9f4a-4b904b60b97b.png)

With bootstarp theme:

![bootstrap3](https://cloud.githubusercontent.com/assets/1502169/19375289/1f5b1848-9205-11e6-8de2-e9ded4291c9a.png)

**Comment by Avernial** [comment]
I found that in template frontend/components/primaryNavMenu.tpl missing block for contact:

{if $currentJournal->getSetting('mailingAddress') || $currentJournal->getSetting('contactName')}
	<li>
	    <a href="{url router=$smarty.const.ROUTE_PAGE page="about" op="contact"}">
		    {translate key="about.contact"}
	    </a>
	</li>
{/if}

**Comment by NateWr** [comment]
Thanks @Avernial! Are you able to submit a Pull Request with this change?

**Comment by Avernial** [comment]
I've submited the pull request #39

**Comment by NateWr** [comment]
:ship:
