### ISSUE TITLE
<h1> should not be the site name

### ISSUE THREAD

**Issue by judgej** [NateWr/bootstrap3#40]
I noticed the site name is wrapped in a `<h1>` element. That is poor practice for a number of reasons.

The `<h1>` element should present the title of the page, not the site. The `<h1>` page name is usually used in search results, and so ranks very low if all pages are the same.

This was even pointed out by the design lead of the `gov.uk` sites when he gave a talk on accessibility last month - screen readers put a lot of emphasis on the header element structure of the page, and is the main navigation used for skipping sections of the page, so that first `<h1>` needs to tell the site visitor what that _page_ is all about.

Additionally, when the site title is replaced with an image, the `<h1>` element does not even contain any text.

**Comment by judgej** [comment]
Some examples here:

http://www.maxability.co.in/2014/08/heading-structure-accessibility/

Some great SO answers here:

http://webmasters.stackexchange.com/questions/4515/h1-vs-h2-vs-other-for-website-title-logo-and-seo

**Comment by NateWr** [comment]
Hi @judgej, the site name should only be wrapped in an `<h1>` tag on the homepage. That's what the `$requestedOp` check is doing in this code:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/components/header.tpl#L115-L119

Other pages should assign the `<h1>` tag correctly, as it's done in these for example:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/about.tpl#L20
https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/editorialTeam.tpl#L20

However, I notice that some templates don't have a properly assigned `<h1>`. This is typically when they make use the breadcrumbs component from Bootstrap, which doesn't play well with `<h1>` styles. I'd definitely be open to a PR that included properly hidden `<h1>` elements in the breadcrumbs where appropriate, and some basic styles to ensure these fit Bootstrap's breadcrumb component.

**Comment by judgej** [comment]
Ah, right, I didn't spot that - just saw it in the header template. Those pages that *do* have titles use the h1 element. Those pages that don't (e.g. archives, current issue) at least don't use it wrapped around the page title.

I'll explore a little more and do a PR if I'm able to add any missing h1s :-)
