### ISSUE TITLE
How should this theme be customised?

### ISSUE THREAD

**Issue by judgej** [NateWr/bootstrap3#41]
I'm unclear how this theme would be customised, i.e. with changes to the CSS, JS and layout (templates). Where would overriding custom styles (CSS, less?) templates etc. go, assuming the base theme is to remain upgrade-safe?

Or is that not possible?

**Comment by NateWr** [comment]
The theming api in OJS 3 supports child themes. Documentation on this is still a little bit light, but you'll find some initial documentation in this [sample child theme](https://github.com/NateWr/default-manuscript) of the default theme.

You'll find a bit more info in [this post on the forum](http://forum.pkp.sfu.ca/t/ojs-3-need-help-with-theme-customization/21210/2?u=natewr) and you'll find a more complete (CSS-only) child theme [here](https://github.com/NateWr/default-manuscript).

At the recent sprint in Montreal, a team did some initial work on getting more documentation ready for this. But I don't think it's been made publicly available yet. That's all in the pipeline and something I'd like to work on over the next few months.

If you have any further questions, I'd invite you to ask on the PKP forums. I will certainly help out wherever, but on the forums there are several people who might share your same questions and benefit from the answers. So for now that's our best place for centralizing general questions about theming OJS 3.

**Comment by judgej** [comment]
Okay, thanks. I asked here because I wasn't aware of child themes, so wasn't sure just how standalone it was. Now I know, it makes more sense to move any further questions over there, since - as you point out - it is general to all 3.0 themes.
