### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by meteakca** [NateWr/bootstrap3#42]
Hi, 
I followed the instructions and extracted the plugin into the themes folder. I get the following error now when I click on the "System Plugins" link:

`Fatal error: require_once(): Failed opening required 'lib/pkp/classes/plugins/ThemePlugin.inc.php' (include_path='.:/home/scipie/public_html/classes:/home/scipie/public_html/pages:/home/scipie/public_html/lib/pkp:/home/scipie/public_html/lib/pkp/includes:/home/scipie/public_html/lib/pkp/classes:/home/scipie/public_html/lib/pkp/pages:/home/scipie/public_html/lib/pkp/lib/adodb:/home/scipie/public_html/lib/pkp/lib/phputf8:/home/scipie/public_html/lib/pkp/lib/pqp/classes:/home/scipie/public_html/lib/pkp/lib/smarty:.:/usr/lib/php:/usr/local/lib/php') in /home/scipie/public_html/lib/pkp/includes/functions.inc.php on line 25`

**Comment by NateWr** [comment]
Hi @meteakca. It doesn't look like you're using OJS 3.0. This theme is not compatible with older versions of OJS.

**Comment by meteakca** [comment]
Got it, thanks. I was trying to install it on OCS :/
