### ISSUE TITLE
Author biography in article details missing

### ISSUE THREAD

**Issue by mittinatten** [NateWr/bootstrap3#50]
Hi,
The editors of a journal I'm admin for wanted to include the author biography in article view. I made some simple changes to the theme: https://github.com/ubbdst/ojs/commit/d6e2078b8d7d18cbf2462a9b403f391d37559418 to accomodate this. Basically I just copied the corresponding section from the standard OJS template and changed some tags. Don't know how well my solution plays with the rest of the code, but it works for our particular journal and theme, perhaps there are other more appropriate tags (`<h5>` is a bit arbitrary for instance) in some places.

We keep the theme directly in our OJS fork, and not as a submodule, for now, so can't do a pull request.

**Comment by NateWr** [comment]
Thanks @mittinatten. I'll try to get this implemented for the next version.

**Comment by mittinatten** [comment]
I have a version ready for a pull request now. Let me know if that's something you can use.

**Comment by NateWr** [comment]
Cheers! I've merged that PR now. :+1:

**Comment by NateWr** [comment]
Woops, that last comment was meant for #54

**Comment by mittinatten** [comment]
Great :)

So the PR I'm talking about here is from this branch https://github.com/ubbdst/bootstrap3/tree/add-author-biography. But as I said initally there's probably room for improvement.
