### ISSUE TITLE
Google Scholar indexing accessible menu as article title

### ISSUE THREAD

**Issue by NateWr** [NateWr/bootstrap3#57]
The accessible menu title should not be wrapped in a `<h2>`:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/components/header.tpl#L30

Google Scholar seems to be indexing that as the article title:

https://scholar.google.com/scholar?q=%22Quick+jump+to+page+content%22&btnG=&hl=en&as_sdt=0%2C5

**Comment by asmecher** [comment]
@NateWr, if you can write up a quick summary of what Scholar could be doing better, I'll pass it along.

**Comment by NateWr** [comment]
@asmecher The algorithm seems to be ignoring the `<title>` tag in the header as well as an `<h1>` which contains the article title, which is nested under the `role=main` section. It's probably our fault for adding that `<h2>` out of order at the top (we'll remove it). But it still seems strange that it's ignoring the other signals.
