### ISSUE TITLE
Missing file bootstrap3.less

### ISSUE THREAD

**Issue by asmecher** [NateWr/bootstrap3#59]
@NateWr, per https://github.com/NateWr/bootstrap3/blob/master/BootstrapThreeThemePlugin.inc.php#L30 this plugin expects a `styles/bootstrap3.less` to exist, but it doesn't -- there's a `bootstrap.less` file instead. I think this is the cause of http://forum.pkp.sfu.ca/t/problem-with-css/31267.

**Comment by NateWr** [comment]
Actually, the base bootstrap file is loaded every time as it forms the basis for the others:

https://github.com/NateWr/bootstrap3/blob/master/BootstrapThreeThemePlugin.inc.php#L51

Still, that `bootstrap3` is making a call to a non-existent file. This code needs to check if the option is `bootstrap3` and not try to add an additional style:

https://github.com/NateWr/bootstrap3/blob/master/BootstrapThreeThemePlugin.inc.php#L62-L64
