### ISSUE TITLE
Cannot install plugins 

### ISSUE THREAD

**Issue by alvaradoUMD** [NateWr/bootstrap3#63]
I'm running this vagrant version of OJS 3 https://github.com/mjordan/pkppln_vagrant but when trying to install the bootstrap plugin or any plugin for that matter I get a permissions error. I've tried both at work and on my personal laptop at home...no go either way.

![permission error](https://user-images.githubusercontent.com/31854690/30278613-da2b84b8-96d8-11e7-97ac-c7fc5a979287.png)

**Comment by NateWr** [comment]
Hi @alvaradoUMD, I'd recommend asking on the repository for the vagrant instance. A file permissions issue is going to be at the server level, not with the plugin itself.
