### ISSUE TITLE
[OJS3.1] Missing menu items

### ISSUE THREAD

**Issue by dtwardy** [NateWr/bootstrap3#67]
It seems as if there's some code missing in BootstrapThreeThemePlugin.inc.php. At least in my test environment Bootstrap3 Theme doesn't load any menu items. A quick check with the Default Theme Plugin points to a missing line at the bottom of init().

`$this->addMenuArea(array('primary', 'user'));`

I added it manually in my environment and it gave me the missing menu items back.

**Comment by NateWr** [comment]
Hi @dtwardy,

Make sure you're suing the correct version of the bootstrap3 theme for your version of OJS. You can see a compatibility list here:

https://github.com/NateWr/bootstrap3#version-compatibility

All releases can be found here:

https://github.com/NateWr/bootstrap3/releases
