### ISSUE TITLE
Remove nl2br requests from "submissions" page

### ISSUE THREAD

**Issue by jmacgreg** [NateWr/bootstrap3#70]
https://github.com/NateWr/bootstrap3/blob/6247cd201ef063b7a21d6bb8ae24e23e78ff85ea/templates/frontend/pages/submissions.tpl#L56

This is one example, I think there are one or two more on this page. I believe they have already been removed from the original core PKP-lib template files. They cause unnecessary <br> spaces between text components (eg. between list items or paragraphs).

**Comment by NateWr** [comment]
I think the checklist items should be run through `nl2br`, because they are not a tinymce field. 

However, the copyright notice and author guidelines on that page are tinymce fields, so shouldn't be run through `nl2br`. This is an issue in core as well. Filed at pkp/pkp-lib#3161

**Comment by NateWr** [comment]
Merged PR: https://github.com/NateWr/bootstrap3/pull/71
