### ISSUE TITLE
Update article display to work with HTML as well as PDF

### ISSUE THREAD

**Issue by jmacgreg** [NateWr/bootstrap3#72]
Re: this line: https://github.com/NateWr/bootstrap3/blob/ec6409f2e06a51debded989c0b641fcb9fb2a152/styles/bootstrap.less#L224

I think it can be changed to: 

`#pdfCanvasContainer, #htmlContainer {`

... and all will be well. :-)

**Comment by NateWr** [comment]
I'd rather follow the way we do it in OJS:

https://github.com/pkp/ojs/blob/master/plugins/themes/default/styles/pages/viewPdf.less#L108-L122

That will be more agnostic so if we add another galley view in an iframe it will work without needing an update.
