### ISSUE TITLE
Mark required form fields

### ISSUE THREAD

**Issue by dennmuel** [NateWr/bootstrap3#77]
Hi everyone,

first of all: thanks a lot for these themes. They look and feel pretty nice. :)
However, I'd like to know if it is possible to mark required form fileds (e.g. for user registration) or if this could be taken into the next release. I know that these themes "may not support all features of OJS 3.0", but perhaps this might be useful for all users.

Kind regards
Dennis

**Comment by NateWr** [comment]
Hi @dennmuel, I'd be open to a contribution which flagged the required fields. Are you able to make the change and issue a Pull Request?

**Comment by dennmuel** [comment]
Hi @NateWr , I'll see what I can do and come back to you later.

**Comment by dennmuel** [comment]
Hi @NateWr , I issued a PR, hoping I didn't overlook any other forms than the registration form.
