### ISSUE TITLE
maquetacion en OJS 3.x primeros pasos

### ISSUE THREAD

**Issue by CARLOSLHG** [NateWr/bootstrap3#79]
Hola a todos,
he creado este Issues porque tengo problemas para modificar el theme creado por @NateWr y su equipo. podrían hacer un ejemplo sobre como agregar una imagen de fondo en el header y agregar un menú lateral lado izquierdo. 

para mortales¡¡¡¡

**Comment by NateWr** [comment]
Hi @CARLOSLHG, you might find some of the documentation in the PKP Theming Guide useful. I'm afraid that's all I can provide. These issues are really just for reporting bugs or feature requests for the theme.

**Comment by NateWr** [comment]
The theming guide can be found here: https://www.gitbook.com/book/pkp/pkp-theming-guide/details
