### ISSUE TITLE
Archive blank page

### ISSUE THREAD

**Issue by kctadmin** [NateWr/bootstrap3#83]
Hi,
I am using ojs 3.1.1.0 in localhost xampp v3.2.2, when i click Archive in my website it directed to a blank page.

this is the error shown in error log

PHP Fatal error:  Uncaught Error: Call to a member function getPageCount() on array in C:\\xampp\\htdocs\\ojs\\cache\\t_compile\\b1833e07cde48b95bfa6dfe66d9ad2430979a526^%%6B^6B5^6B5271FB%%issueArchive.tpl.php:6\nStack trace:\n#0 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\Smarty.class.php(1257): include()\n#1 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\template\\PKPTemplateManager.inc.php(797): Smarty->fetch('frontend/pages/...', NULL, 'b1833e07cde48b9...', true)\n#2 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\Smarty.class.php(1107): PKPTemplateManager->fetch('frontend/pages/...', NULL, 'b1833e07cde48b9...', true)\n#3 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\template\\PKPTemplateManager.inc.php(872): Smarty->display('frontend/pages/...', NULL, NULL)\n#4 C:\\xampp\\htdocs\\ojs\\pages\\issue\\IssueHandler.inc.php(152): PKPTemplateManager->display('frontend/pages/...')\n#5 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\core\\PKPRouter.inc.php(372): IssueHandler->archive(Array, Object(Request))\n#6 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\core\\PKPPageRo in C:\\xampp\\htdocs\\ojs\\cache\\t_compile\\b1833e07cde48b95bfa6dfe66d9ad2430979a526^%%6B^6B5^6B5271FB%%issueArchive.tpl.php on line 6, referer: http://localhost/OJS/index.php/art/index

Please help to solve this problem

**Comment by kctadmin** [comment]
Hi, Just now i noticed that Archive is not working when using child theme. but it is working fine in bootstrap3. Please give some suggestion.

<?php

/**
 * @file plugins/themes/default/kctChildThemePlugin.inc.php
 *
 * Copyright (c) 2014-2016 Simon Fraser University Library
 * Copyright (c) 2003-2016 John Willinsky
 * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
 *
 * @class kctChildThemePlugin
 * @ingroup plugins_themes_default
 *
 * @brief Default theme
 */
import('lib.pkp.classes.plugins.ThemePlugin');

class kctChildThemePlugin extends ThemePlugin { 
	/**
	 * Initialize the theme's styles, scripts and hooks. This is only run for
	 * the currently active theme.
	 *
	 * @return null
	 */
	 public function init() {
        $this->setParent('bootstrapthreethemeplugin');
		//$this->addStyle('stylesheet', 'styles/variables.less');
		
        //$this->modifyStyle('bootstrap', array('addLess' => array('styles/variables.less')));
		
		$this->addStyle('stylesheet', 'styles/stylesheet.css');
		
		//$this->modifyStyle('stylesheet', array('addLessVariables' => '@navbar-height:50px;'));
		
		
		
		
		
    }
	/**
	 * Get the display name of this plugin
	 * @return string
	 */
	function getDisplayName() {
		return __('plugins.themes.kct-child.name');
	}

	/**
	 * Get the description of this plugin
	 * @return string
	 */
	function getDescription() {
		return __('plugins.themes.kct-child.description');
	}
}

?>


this is my child theme

**Comment by kctadmin** [comment]
Can you please guide me to match pagination pattern ?

**Comment by NateWr** [comment]
https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/issueArchive.tpl#L43-L59

**Comment by kctadmin** [comment]
hi,
Problem Solved. Thank you very much.
