### ISSUE TITLE
Replace |assign format for upgrade to smarty v3

### ISSUE THREAD

**Issue by NateWr** [NateWr/bootstrap3#84]
We use `{url|assign...` and `{translate|assign...` throughout the theme. This will not longer be valid Smarty once the upgrade to v3 is merged in (https://github.com/pkp/pkp-lib/issues/3242).

We need to use `{capture}` instead. But we also need to be careful to not introduce white-space that can cause conditional errors, like the `$prevUrl` and `$nextUrl` issue that @Vitaliy found: https://github.com/pkp/pkp-lib/issues/3652

**Comment by asmecher** [comment]
@NateWr, this recently came up for OJS 3.1.2 at https://forum.pkp.sfu.ca/t/3-1-2-upgrade-error/51707/4.

**Comment by NateWr** [comment]
That issue was fixed in https://github.com/NateWr/bootstrap3/issues/115. The 3.1.2 branches should fix this and should be merged to `master` at some point.

**Comment by NateWr** [comment]
I cherry-picked this to 3.2 so it will be included when that is merged to master.
