### ISSUE TITLE
Hide search field in head on site index

### ISSUE THREAD

**Issue by NateWr** [NateWr/bootstrap3#86]
The current logic doesn't seem to check for a current context. It should look like  https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/header.tpl#L73-L90

**Comment by jafamo** [comment]
HI, I am interested to use this feature in my bootstrap3 theme, I tried to use a main.js and styles from default theme but it's still not working properly.
I am using ojs 3_1__1_4 

Do you know how can I used this feature ??

Regards,
jafamo

**Comment by NateWr** [comment]
To implement this you would need to change these lines in the template file:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/components/header.tpl#L111-L115

Either by customizing your own theme or using a child theme. See the [theming guide](https://docs.pkp.sfu.ca/pkp-theming-guide/en/).
