### ISSUE TITLE
Resizing Sidebars (Block Bars) for IndexSite

### ISSUE THREAD

**Issue by EduardoOsquel** [NateWr/bootstrap3#87]
The site that I support (https://revistas.reduc.edu.cu/), is a multisite that contains 7 journals and the main page (IndexSite) works with a template (that I modified) based on bootstrap3 of @NateWr. In a virtual test machine I tried to resize the blocks in the right sidebar, but when I try to modify bootstrap-rtl.min.css it seems to have no effect.
What I can do? Greetings Eduardo Osquel

**Comment by EduardoOsquel** [comment]
![bootstrap-resizing](https://user-images.githubusercontent.com/37707937/40661977-0f7695d8-6323-11e8-9f12-4162d0dee62f.png)
Este es el ejemplo!!

**Comment by NateWr** [comment]
Hi @EduardoOsquel,

`bootstrap-rtl.min.css` is only loaded for right-to-left languages (Arabic/Hebrew). Instead of modifying a file, I'd recommend you use the CSS upload feature under Settings > Website > Appearance to upload your own .css file. This will keep your changes separate from the plugin so that it's easier to update without losing your changes.

**Comment by EduardoOsquel** [comment]
Good Morning @NateWr ,
yesterday, inadvertently, I did not check the mail, and I did not realize the solution that you propose that is undoubtedly the most efficient. I found another way, insert a custom.css file in the bootstrap3/styles root and load it through lib/pkp/templates/frontend/components/headerHead.tpl. Thank you for helping me with the doubt, I did not know that rtl meant right-to-left. Greetings Eduardo Osquel

**Comment by NateWr** [comment]
Glad you were able to figure out a solution. You should know, though, that any changes you make in the theme directory will be removed when you update the theme. It's best to use the option under Settings > Website > Appearance, since that will not be removed when you update the theme.

**Comment by EduardoOsquel** [comment]
Thanks @NateWr, I adjusted it following the advice you gave me in the previous message. It is obvious that I do not want to lose any modifications in the next update of the OJS and the bootstrap3 template. I do not know when it will be available but; Have you contemplated the idea of making the page that groups all the journals (indexSite.tpl) and the site of each of them (indexJournal.tpl) show the content in a different way? For example, in my case, I have a multisite with 7 journals from the University where I work as a teacher and webmaster, and I had to make modifications on the main page so that all the magazines would be "on the same level", because the Managers of the magazine that was at the end of the page complained because they said that users never scroll until the bottom of the page. Stupid, but true hahaha.

**Comment by NateWr** [comment]
We'll probably leave the default implementation as-is, since we can't know how many journals a particular site will have. But please do share your work on the community forums. 

This theme was meant to be a starting point for the community, and sharing your customizations can help other people who need to solve the same problem.

**Comment by EduardoOsquel** [comment]
Goog morning @NateWr,
With your permission, I will upload the complete project (the bootstrap3 folder), to share the work I have been doing. I have to warn that the code is not debugged, it's like a beta version. Since I have been working with the University website for a short time. 
Greetings Eduardo Osquel

**Comment by NateWr** [comment]
Great! Be sure to post about it in the [Community Showcase](https://forum.pkp.sfu.ca/c/community-showcase) when it's up.
