### ISSUE TITLE
Privacy options missing from registrationForm.tpl

### ISSUE THREAD

**Issue by RichardPilbery** [NateWr/bootstrap3#88]
In order to register as a user in OJS 3.1.1 you have to agree to the terms of the privacy statement. However, this is missing from: templates/frontend/components/registrationForm.tpl in this theme. Quick copy-and-paste required.

**Comment by NateWr** [comment]
Thanks for reporting @RichardPilbery. I've released an update ([v1.1.3](https://github.com/NateWr/bootstrap3/releases/tag/1.1.3)) with a fix for this.
