### ISSUE TITLE
Use colon consistently in article sidebar

### ISSUE THREAD

**Issue by NateWr** [NateWr/bootstrap3#94]
The article sidebar displays three items with a label and a value: date, doi and keywords. They should all use a colon like Keywords.

![selection_041](https://user-images.githubusercontent.com/2306629/43650754-8a3f3952-9738-11e8-95c8-9f82cc26efe3.png)

**Comment by anupent** [comment]
Hi @NateWr , see this Pull request:
https://github.com/NateWr/bootstrap3/pull/95
