### ISSUE TITLE
modifyStyle instead of addStyle for Bootstrab sub-themes

### ISSUE THREAD

**Issue by aguen** [NateWr/bootstrap3#96]
In BootstrapThreeThemePlugin.inc.php: Why don't you use modifyStyle for  css of sub-themes? Currently, two complete bootstrap css Files are loaded:

`$this->addStyle('bootstrapTheme-' . $bootstrapTheme, 'styles/' . $bootstrapTheme . '.less');`

This would be prevented with:

`$this->modifyStyle('bootstrapTheme-' . $bootstrapTheme, array('addLess' => array('styles/'. $bootstrapTheme . '.less')));`

Besides better performance, it would simplify debugging/editing styles?

**Comment by aguen** [comment]
Yes, I see two bootstrap files. I think that the first is included by:

`$this->addStyle('bootstrap', 'styles/bootstrap.less');`

and the second added by 

```
if (!empty($bootstrapTheme) && $bootstrapTheme !== 'bootstrap3') {
	$this->addStyle('bootstrapTheme-' . $bootstrapTheme, 'styles/' . $bootstrapTheme . '.less');
}
```
For example, I have selected the "united" option (sub-thema) and in the HTML file the following two complete bootstrap variants are included:
```
<link rel="stylesheet" href="https://jbdgm.psychopen.eu/index.php/JBDGM/$$$call$$$/page/page/css?name=bootstrap" type="text/css" />
<link rel="stylesheet" href="https://jbdgm.psychopen.eu/index.php/JBDGM/$$$call$$$/page/page/css?name=bootstrapTheme-united" type="text/css" />
```
File 1 (bootstrap) has 1214 CSS rules, file 2 (bootstrapTheme-united) 1218 - as you can verify online. bootstrapTheme-united seems to include all Bootstrap rules not only the modified. Or am I doing something wrong?

Actually I use a child thema that adds two further stylesheets (see below), perhaps this is the problem?

```
	public function init() {
		$this->setParent('bootstrapthreethemeplugin');
		$this->addStyle('jbdgm','styles/jbdgm_style.css');
		$this->addStyle('fontawesome','styles/fontawesome/css/all.css');
		HookRegistry::register ('TemplateManager::display', array($this, 'loadTemplateData')); 
    
	}
```
Best
Armin

**Comment by NateWr** [comment]
I think you may be using an out-dated version of the Bootstrap3 theme. In the current `master` branch, only one `addStyle` call is made depending on the conditional:

https://github.com/NateWr/bootstrap3/blob/master/BootstrapThreeThemePlugin.inc.php#L51-L56

**Comment by NateWr** [comment]
It looks like this was fixed in January: https://github.com/NateWr/bootstrap3/commit/33ef0a4363293dd65bdecbfa633d18cd99bbc6a1#diff-0a050d49badc70b143c726ad4221dc73

**Comment by aguen** [comment]
Yes, sorry, it's fixed and I should have checked this, my fault. 

Thank you for your good work! 

Best, Armin

**Comment by NateWr** [comment]
No problem! Not always easy to keep up with the changes around here. I had totally forgotten about it even though I fixed it 6 months ago. :)

**Comment by aguen** [comment]
;-
